spring:
  profiles:
    active: ${PROFILE.ACTIVE}
  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:postgresql://${SERVER_HOST:localhost}:${SERVER_PORT:5432}/${DB_NAME:traveloka}
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:postgres}
    driverClassName: org.postgresql.Driver
  sql:
    init:
      platform: postgres
  liquibase:
    change-log: classpath:db/master.xml

server:
  port: 8000

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE