spring:
    data:
      mongodb:
        authentication-database: admin
        username: admin
        password: admin
        database: hotel
        port: 27017
        host: ${SERVER_HOST}
logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: DEBUG